Feat v1.3 update sales page, create rule view UI & mechanics
immutable-bee/fashionpal pull request #43
Opened 2024-01-17 19:07 UTC by bali710

2024-01-17 19:26 UTC, immutable-bee requested changes
The "SALE"/"STANDARD" checkbox highlight will switch to "SALE" when clicked but won't switch back to "STANDARD" when clicked again.

2024-01-17 19:26 UTC, immutable-bee commented on components/scoped/CreateNewRule.js
Update Line 168: 

"setType("standard");"

 to

"setType("STANDARD");"

2024-01-17 19:26 UTC, immutable-bee commented on pages/api/pricing-rules/add.js
lgtm

2024-01-17 19:26 UTC, immutable-bee commented on pages/api/pricing-rules/update.js
lgtm

2024-01-17 19:26 UTC, immutable-bee commented on prisma/schema.prisma
lgtm

2024-01-18 12:27 UTC, bali710 commented on components/scoped/CreateNewRule.js
I ask Ibrahim for this change He is already taking care of this in another branch

2024-01-18 12:34 UTC, merged